### ISSUE TITLE
Error in oe_generate_legend.py creating legend for xml with one value in final colormap entry

### ISSUE THREAD

**Issue by srussking** [nasa-gibs/onearth#46]
Got this error for the xml (
http://map1b.vis.earthdata.nasa.gov/colormaps/AIRS_RelativeHumidity_400hPa_Day.xml) with oe_generate_legend.py

```python
   <ColorMapEntry rgb="161,0,3" transparent="False" nodata="False" sourceValue="[98,99)" value="[98,99)" label="98 – 99 %" ref="0"/>
    <ColorMapEntry rgb="151,0,3" transparent="False" nodata="False" sourceValue="[99,100)" value="[99,100)" label="99 – 100 %" ref="0"/>
    <ColorMapEntry rgb="142,0,3" transparent="False" nodata="False" sourceValue="[100]" value="[100]" label="100 %" ref="0"/>
</ColorMap>

Traceback (most recent call last):
  File "/Users/russ/Rails/airs_rails/lib/assets/oe_generate_legend.py", line 952, in <module>
    generate_legend(colormaps, output_location, options.format, options.orientation)
  File "/Users/russ/Rails/airs_rails/lib/assets/oe_generate_legend.py", line 467, in generate_legend
    increment = (float(colormap_entries[idx].value) - float(colormap_entries[idx-1].value))
ValueError: could not convert string to float: [99,100)
```
Even though the catch seems to be reporting on the [99,100) it is definitely on the [100] piece when it explodes.

Changed the else clause at line 463:
```
else:
   increment = (float(colormap_entries[idx].value) - float(colormap_entries[idx-1].value))
   bounds.append(float(colormap_entries[idx].value)+ increment)
   ticks.append(float(colormap_entries[idx].value) + increment/2)
   ticklabels.append(float(colormap_entries[idx].value))
```
and removed the lines referencing increment, so that the clause is now just 
```
   ticklabels.append(float(colormap_entries[idx].value))
```

Which works, and the resulting image looks good, but not sure if I have broken something else...

**Comment by jtroberts** [comment]
I'll test out the change sometime soon to see if it would cause any problems. Thanks for the report!

**Comment by jtroberts** [comment]
This portion of the code has been removed in the latest version of OnEarth.
